modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL=""
license="${mod_license}"
logoFile="${mod_icon}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="${credits}"
displayURL=""
authors="${mod_author}"
description='''
${mod_description}
'''
[[dependencies."${mod_id}"]]
modId="forge"
mandatory=true
versionRange="%{forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies."${mod_id}"]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies."${mod_id}"]]
modId="lootr"
mandatory=false
versionRange="*"
ordering="AFTER"
side="BOTH"
